 
name: 'docker test'
author: 'triptixx'
description: 'A Action CI plugin for start and test build Docker images'
inputs:
  repo:
    description: 'tag for the image to run and test'
    required: true
  docker_network_id:
    description: 'id of the container network'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'
  color: 'blue'
