 
name: 'docker test'
author: 'triptixx'
description: 'A Action CI plugin for start and test build Docker images'
inputs:
  verbose:
    description: 'print curl output and running commands'
    default: false
  repo:
    description: 'tag for the image to run and test'
    required: true
  delay:
    description: 'startup delay for the container before executing any actions'
    default: 10
  retry:
    description: 'curl retry count before giving up'
    default: 5
  retry_delay:
    description: 'curl delay before retrying'
    default: 5
  timeout:
    description: 'time output logs container'
    default: 10
  run:
    description: 'run a command in a test container and exit'
  run_args:
    description: 'arguments to pass to docker create'
  run_cmd:
    description: 'override docker container CMD'
  curl:
    description: 'url path to curl'
  curl_opts:
    description: 'additional options to pass to curl'
  pipe:
    description: 'shell code to execute on curl output'
  log_pipe:
    description: 'shell code to execute on logs container output'
  exec_pre:
    description: 'shell commands inside the container to run before curl'
  exec_post:
    description: 'shell commands inside the container to run after curl'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'
  color: 'blue'
